### ISSUE TITLE
`test_rr_broken.py` is breaking all test cases

### ISSUE THREAD

**Issue by adamdoupe** [shellphish/rex#48] opened 2019-04-18 20:24 UTC
The test cases don't pass (in part) because of the newly added `test_rr_broken.py`. 

The major problem is that this test case hangs and no others are executed (my guess is that it's because rr is not installed on the travis environment, as I can replicate this same behavior on my machine).

https://travis-ci.org/shellphish/rex/builds/521542046?utm_source=github_status&utm_medium=notification

**Comment by adamdoupe** [comment] 2019-04-18 20:33
ok, all the test cases are running now (that old link was on a branch where I didn't merge latest),

but the rr test cases are still failing, I think the docker image needs to get built (we can look to the archr tests for that):
https://travis-ci.org/shellphish/rex/jobs/521900930#L1040

**Comment by ltfish** [comment] 2019-04-18 20:33
If it's broken, it should be named `broken_xxx.py` so it will be not executed on the CI.

**Comment by adamdoupe** [comment] 2019-04-18 20:34
I agree @ltfish , but the `broken` part of the name comes from our hackathon testing time, so I don't think that's what was intended with the name.

**Comment by Lukas-Dresel** [comment] 2019-04-18 20:58
@adamdoupe That was intended, but I thought it was if _broken is in the name :P 
However, that testcase is no longer needed. I'll remove it.

**Comment by Lukas-Dresel** [comment] 2019-04-18 20:59
wait, where is it? I actually already removed it

**Comment by rhelmot** [comment] 2019-04-18 20:59
The logic is that anything with test_ is picked up. It's a white list, not
a blacklist. Now you know!

**Comment by Lukas-Dresel** [comment] 2019-04-18 22:54
should be fixed now hopefully

**Closed by Lukas-Dresel** 2019-04-18 22:54 UTC
Labels: bug
